FROM tensorflow/tensorflow:1.14.0-gpu-py3

ENV SRC_DIR /src

COPY src $SRC_DIR
WORKDIR $SRC_DIR

RUN apt-get update
RUN apt-get install -y -q python-all python-pip 


RUN chmod +x ./train.sh ./inference.sh
RUN pip install pytest
RUN pip install keras
RUN pip install nibabel
RUN pip install matplotlib
RUN pip install itertools
RUN pip install -U --pre segmentation-models
RUN pip install -U albumentations>=0.3.0 --user

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
